language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  # install cython
  - pip install -U Cython
  # install gd.py with asyncio pytest plugin
  - pip install -U .[dev]
  # install coveralls
  - pip install -U coveralls

script:
  # run lint
  - flake8
  # run tests and check coverage
  - coverage run -m pytest ./tests/ --maxfail=3 --disable-warnings

after_success:
  # report to coveralls
  - coveralls
